---
framework: mocha
postMerge:
  pattern:
    - "./lib/**/*/__tests__/*.js"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./lib/**/*/__tests__/*.js"
preRun:
  - npm i
  - npm install svgexport -g --unsafe-perm=true
postRun:
  - node --version
configFile: mocha.opts
version: 2.0
