---
framework: mocha
postMerge:
  pattern:
    - "./lib/**/*/__tests__/*.js"
preMerge:
  pattern:
    - "./lib/**/*/__tests__/*.js"
preRun:
  command:
    - npm i
    - npm install svgexport -g --unsafe-perm=true
postRun:
  command:
    - node --version
configFile: mocha.opts
version: 2.1
